/**
 * XP Curve Generator
 *
 * This script generates the XP lookup table for skill progression.
 * Modify the tier definitions below to rebalance the leveling curve,
 * then run: npm run generate:xp-curve
 *
 * The output will be a TypeScript constant array that you can copy into
 * shared/constants/attribute-constants.ts
 */

interface XPTier {
  minLevel: number;
  maxLevel: number;
  xpPerLevel: number;
}

// ===== CONFIGURE YOUR XP CURVE HERE =====

const XP_TIERS: XPTier[] = [
  { minLevel: 1,  maxLevel: 10,  xpPerLevel: 100 },   // Fast early progression
  { minLevel: 11, maxLevel: 20,  xpPerLevel: 500 },   // Unlocking tier 2 content
  { minLevel: 21, maxLevel: 30,  xpPerLevel: 1500 },  // Mid-game grind
  { minLevel: 31, maxLevel: 40,  xpPerLevel: 3000 },  // Late-game commitment
  { minLevel: 41, maxLevel: 50,  xpPerLevel: 5000 },  // Endgame mastery
];

const MAX_LEVEL = 50;

// ===== GENERATOR LOGIC =====

function generateXPCurve(): number[] {
  const xpPerLevel: number[] = [0]; // Level 0 placeholder

  for (let level = 1; level <= MAX_LEVEL; level++) {
    const tier = XP_TIERS.find(t => level >= t.minLevel && level <= t.maxLevel);

    if (!tier) {
      // If level exceeds defined tiers, use last tier's XP
      const lastTier = XP_TIERS[XP_TIERS.length - 1];
      xpPerLevel.push(lastTier.xpPerLevel);
    } else {
      xpPerLevel.push(tier.xpPerLevel);
    }
  }

  return xpPerLevel;
}

function calculateStats(xpCurve: number[]): void {
  console.log('\n=== XP CURVE STATISTICS ===\n');

  let totalXP = 0;
  let tierStart = 1;

  for (const tier of XP_TIERS) {
    const tierXP = (tier.maxLevel - tier.minLevel + 1) * tier.xpPerLevel;
    totalXP += tierXP;

    console.log(`Levels ${tier.minLevel}-${tier.maxLevel}:`);
    console.log(`  XP per level: ${tier.xpPerLevel}`);
    console.log(`  Total tier XP: ${tierXP.toLocaleString()}`);
    console.log(`  Cumulative XP: ${totalXP.toLocaleString()}`);
    console.log('');
  }

  console.log(`Total XP to reach level ${MAX_LEVEL}: ${totalXP.toLocaleString()}`);
  console.log('');

  // Sample progression at key levels
  console.log('=== SAMPLE PROGRESSION ===\n');

  const sampleLevels = [1, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50];

  for (const level of sampleLevels) {
    if (level > MAX_LEVEL) continue;

    let cumulativeXP = 0;
    for (let i = 1; i < level; i++) {
      cumulativeXP += xpCurve[i];
    }

    const xpForNext = xpCurve[level] || 0;
    console.log(`Level ${level}: ${cumulativeXP.toLocaleString()} total XP | ${xpForNext} XP to next`);
  }

  console.log('');
}

function formatAsTypeScript(xpCurve: number[]): string {
  const lines: string[] = [
    '/**',
    ' * XP required for each level.',
    ' * Index = level, Value = XP needed to advance to next level',
    ' * Example: XP_PER_LEVEL[5] = XP needed to go from level 5 to level 6',
    ' * ',
    ' * Generated by: be/utils/generate-xp-curve.ts',
    ' * DO NOT EDIT MANUALLY - run npm run generate:xp-curve instead',
    ' */',
    'export const XP_PER_LEVEL: readonly number[] = [',
  ];

  // Group by tiers for readability
  let currentTier = 0;

  for (let i = 0; i < xpCurve.length; i++) {
    const level = i;
    const xp = xpCurve[i];

    // Add tier comment
    if (currentTier < XP_TIERS.length && level === XP_TIERS[currentTier].minLevel) {
      const tier = XP_TIERS[currentTier];
      lines.push(`  // Levels ${tier.minLevel}-${tier.maxLevel}: ${tier.xpPerLevel} XP per level`);
      currentTier++;
    }

    if (level === 0) {
      lines.push(`  0,  // Level 0 (placeholder)`);
    } else {
      const comment = level === MAX_LEVEL ? `  // Level ${level}→${level + 1}` : '';
      lines.push(`  ${xp},${comment}`);
    }
  }

  lines.push('] as const;');

  return lines.join('\n');
}

// ===== RUN GENERATOR =====

console.log('=== XP CURVE GENERATOR ===');
console.log(`Generating curve for levels 1-${MAX_LEVEL}...\n`);

const xpCurve = generateXPCurve();

calculateStats(xpCurve);

console.log('=== GENERATED TYPESCRIPT CODE ===\n');
console.log('Copy the following into shared/constants/attribute-constants.ts:\n');
console.log('─'.repeat(80));
console.log(formatAsTypeScript(xpCurve));
console.log('─'.repeat(80));
console.log('\n✅ Generation complete!\n');
