/**
 * Vendors Registry - Central registry for all vendors
 * Auto-generated by scripts/generate-all-registries.ts
 * Generated: 2025-11-18T01:41:54.824Z
 * DO NOT EDIT MANUALLY
 */

import { Vendor } from '../../types/crafting';

import { ForestClearingMerchant } from './ForestClearingMerchant';
import { KennikCook } from './KennikCook';
import { KennikDockMerchant } from './KennikDockMerchant';
import { KennikHerbGardenMerchant } from './KennikHerbGardenMerchant';
import { KennikPotionSeller } from './KennikPotionSeller';
import { MountainMineMerchant } from './MountainMineMerchant';

/**
 * Central registry for all vendors
 */
export class VendorRegistry {
  private static readonly items = new Map<string, Vendor>([
    [ForestClearingMerchant.vendorId, ForestClearingMerchant],
    [KennikCook.vendorId, KennikCook],
    [KennikDockMerchant.vendorId, KennikDockMerchant],
    [KennikHerbGardenMerchant.vendorId, KennikHerbGardenMerchant],
    [KennikPotionSeller.vendorId, KennikPotionSeller],
    [MountainMineMerchant.vendorId, MountainMineMerchant],
  ]);

  /**
   * Get a vendor by ID
   */
  static get(id: string): Vendor | undefined {
    return this.items.get(id);
  }

  /**
   * Check if a vendor exists
   */
  static has(id: string): boolean {
    return this.items.has(id);
  }

  /**
   * Get all vendors
   */
  static getAll(): Vendor[] {
    return Array.from(this.items.values());
  }

  /**
   * Get all vendor IDs
   */
  static getAllIds(): string[] {
    return Array.from(this.items.keys());
  }

  /**
   * Get the total number of vendors
   */
  static get size(): number {
    return this.items.size
  }
}
