/**
 * Activities Registry - Central registry for all activities
 * Auto-generated by scripts/generate-all-registries.ts
 * Generated: 2025-11-18T01:41:54.826Z
 * DO NOT EDIT MANUALLY
 */

import { ActivityUnion } from '../../types/locations';

import { ActivityChopBirch } from './activities/ActivityChopBirch';
import { ActivityChopOak } from './activities/ActivityChopOak';
import { ActivityChopPine } from './activities/ActivityChopPine';
import { ActivityCombatBandit } from './activities/ActivityCombatBandit';
import { ActivityCombatBandits } from './activities/ActivityCombatBandits';
import { ActivityCombatForestWolf } from './activities/ActivityCombatForestWolf';
import { ActivityCombatGoblin } from './activities/ActivityCombatGoblin';
import { ActivityCombatGoblinScout } from './activities/ActivityCombatGoblinScout';
import { ActivityCombatGoblinShaman } from './activities/ActivityCombatGoblinShaman';
import { ActivityCombatGoblinWarriorVillage } from './activities/ActivityCombatGoblinWarriorVillage';
import { ActivityFishCod } from './activities/ActivityFishCod';
import { ActivityFishSalmon } from './activities/ActivityFishSalmon';
import { ActivityFishShrimp } from './activities/ActivityFishShrimp';
import { ActivityGatherChamomile } from './activities/ActivityGatherChamomile';
import { ActivityGatherDragonsBreath } from './activities/ActivityGatherDragonsBreath';
import { ActivityGatherMandrake } from './activities/ActivityGatherMandrake';
import { ActivityGatherMoonpetal } from './activities/ActivityGatherMoonpetal';
import { ActivityGatherNettle } from './activities/ActivityGatherNettle';
import { ActivityGatherSage } from './activities/ActivityGatherSage';
import { ActivityGatherSand } from './activities/ActivityGatherSand';
import { ActivityMineCopper } from './activities/ActivityMineCopper';
import { ActivityMineIron } from './activities/ActivityMineIron';
import { ActivityMineTin } from './activities/ActivityMineTin';
import { ActivityQuarryStone } from './activities/ActivityQuarryStone';
import { ActivitySawmill } from './activities/ActivitySawmill';

/**
 * Central registry for all activities
 */
export class ActivityRegistry {
  private static readonly items = new Map<string, ActivityUnion>([
    [ActivityChopBirch.activityId, ActivityChopBirch],
    [ActivityChopOak.activityId, ActivityChopOak],
    [ActivityChopPine.activityId, ActivityChopPine],
    [ActivityCombatBandit.activityId, ActivityCombatBandit],
    [ActivityCombatBandits.activityId, ActivityCombatBandits],
    [ActivityCombatForestWolf.activityId, ActivityCombatForestWolf],
    [ActivityCombatGoblin.activityId, ActivityCombatGoblin],
    [ActivityCombatGoblinScout.activityId, ActivityCombatGoblinScout],
    [ActivityCombatGoblinShaman.activityId, ActivityCombatGoblinShaman],
    [ActivityCombatGoblinWarriorVillage.activityId, ActivityCombatGoblinWarriorVillage],
    [ActivityFishCod.activityId, ActivityFishCod],
    [ActivityFishSalmon.activityId, ActivityFishSalmon],
    [ActivityFishShrimp.activityId, ActivityFishShrimp],
    [ActivityGatherChamomile.activityId, ActivityGatherChamomile],
    [ActivityGatherDragonsBreath.activityId, ActivityGatherDragonsBreath],
    [ActivityGatherMandrake.activityId, ActivityGatherMandrake],
    [ActivityGatherMoonpetal.activityId, ActivityGatherMoonpetal],
    [ActivityGatherNettle.activityId, ActivityGatherNettle],
    [ActivityGatherSage.activityId, ActivityGatherSage],
    [ActivityGatherSand.activityId, ActivityGatherSand],
    [ActivityMineCopper.activityId, ActivityMineCopper],
    [ActivityMineIron.activityId, ActivityMineIron],
    [ActivityMineTin.activityId, ActivityMineTin],
    [ActivityQuarryStone.activityId, ActivityQuarryStone],
    [ActivitySawmill.activityId, ActivitySawmill],
  ]);

  /**
   * Get a activityunion by ID
   */
  static get(id: string): ActivityUnion | undefined {
    return this.items.get(id);
  }

  /**
   * Check if a activityunion exists
   */
  static has(id: string): boolean {
    return this.items.has(id);
  }

  /**
   * Get all activities
   */
  static getAll(): ActivityUnion[] {
    return Array.from(this.items.values());
  }

  /**
   * Get all activityunion IDs
   */
  static getAllIds(): string[] {
    return Array.from(this.items.keys());
  }

  /**
   * Get the total number of activities
   */
  static get size(): number {
    return this.items.size
  }
}
