/**
 * Biomes Registry - Central registry for all biomes
 * Auto-generated by scripts/generate-all-registries.ts
 * Generated: 2025-11-12T01:49:56.542Z
 * DO NOT EDIT MANUALLY
 */

import { BiomeDefinition } from '../../types/locations';

import { Forest } from './biomes/Forest';
import { Mountain } from './biomes/Mountain';
import { Sea } from './biomes/Sea';

/**
 * Central registry for all biomes
 */
export class BiomeRegistry {
  private static readonly items = new Map<string, BiomeDefinition>([
    [Forest.biomeId, Forest],
    [Mountain.biomeId, Mountain],
    [Sea.biomeId, Sea],
  ]);

  /**
   * Get a biome by ID
   */
  static get(id: string): BiomeDefinition | undefined {
    return this.items.get(id);
  }

  /**
   * Check if a biome exists
   */
  static has(id: string): boolean {
    return this.items.has(id);
  }

  /**
   * Get all biomes
   */
  static getAll(): BiomeDefinition[] {
    return Array.from(this.items.values());
  }

  /**
   * Get all biome IDs
   */
  static getAllIds(): string[] {
    return Array.from(this.items.keys());
  }

  /**
   * Get the total number of biomes
   */
  static get size(): number {
    return this.items.size
  }
}
