/**
 * DropTables Registry - Central registry for all droptables
 * Auto-generated by scripts/generate-all-registries.ts
 * Generated: 2025-11-18T01:41:54.828Z
 * DO NOT EDIT MANUALLY
 */

import { DropTable } from '@shared/types';

import { CombatBanditBasic } from './drop-tables/CombatBanditBasic';
import { CombatGoblinBasic } from './drop-tables/CombatGoblinBasic';
import { CombatGoblinScout } from './drop-tables/CombatGoblinScout';
import { CombatGoblinShaman } from './drop-tables/CombatGoblinShaman';
import { CombatWolfBasic } from './drop-tables/CombatWolfBasic';
import { FishingCod } from './drop-tables/FishingCod';
import { FishingSalmon } from './drop-tables/FishingSalmon';
import { FishingShrimp } from './drop-tables/FishingShrimp';
import { GatheringChamomile } from './drop-tables/GatheringChamomile';
import { GatheringDragonsBreath } from './drop-tables/GatheringDragonsBreath';
import { GatheringMandrake } from './drop-tables/GatheringMandrake';
import { GatheringMoonpetal } from './drop-tables/GatheringMoonpetal';
import { GatheringNettle } from './drop-tables/GatheringNettle';
import { GatheringSage } from './drop-tables/GatheringSage';
import { GatheringSand } from './drop-tables/GatheringSand';
import { MiningCopper } from './drop-tables/MiningCopper';
import { MiningIron } from './drop-tables/MiningIron';
import { MiningStone } from './drop-tables/MiningStone';
import { MiningTin } from './drop-tables/MiningTin';
import { RareFishing } from './drop-tables/RareFishing';
import { RareLowMining } from './drop-tables/RareLowMining';
import { RareWoodcutting } from './drop-tables/RareWoodcutting';
import { RareWoodcuttingBirch } from './drop-tables/RareWoodcuttingBirch';
import { RareWoodcuttingFinds } from './drop-tables/RareWoodcuttingFinds';
import { RareWoodcuttingOak } from './drop-tables/RareWoodcuttingOak';
import { RareWoodcuttingPine } from './drop-tables/RareWoodcuttingPine';
import { SawmillPlanks } from './drop-tables/SawmillPlanks';
import { WoodcuttingBirch } from './drop-tables/WoodcuttingBirch';
import { WoodcuttingOak } from './drop-tables/WoodcuttingOak';
import { WoodcuttingPine } from './drop-tables/WoodcuttingPine';

/**
 * Central registry for all droptables
 */
export class DropTableRegistry {
  private static readonly items = new Map<string, DropTable>([
    [CombatBanditBasic.dropTableId, CombatBanditBasic],
    [CombatGoblinBasic.dropTableId, CombatGoblinBasic],
    [CombatGoblinScout.dropTableId, CombatGoblinScout],
    [CombatGoblinShaman.dropTableId, CombatGoblinShaman],
    [CombatWolfBasic.dropTableId, CombatWolfBasic],
    [FishingCod.dropTableId, FishingCod],
    [FishingSalmon.dropTableId, FishingSalmon],
    [FishingShrimp.dropTableId, FishingShrimp],
    [GatheringChamomile.dropTableId, GatheringChamomile],
    [GatheringDragonsBreath.dropTableId, GatheringDragonsBreath],
    [GatheringMandrake.dropTableId, GatheringMandrake],
    [GatheringMoonpetal.dropTableId, GatheringMoonpetal],
    [GatheringNettle.dropTableId, GatheringNettle],
    [GatheringSage.dropTableId, GatheringSage],
    [GatheringSand.dropTableId, GatheringSand],
    [MiningCopper.dropTableId, MiningCopper],
    [MiningIron.dropTableId, MiningIron],
    [MiningStone.dropTableId, MiningStone],
    [MiningTin.dropTableId, MiningTin],
    [RareFishing.dropTableId, RareFishing],
    [RareLowMining.dropTableId, RareLowMining],
    [RareWoodcutting.dropTableId, RareWoodcutting],
    [RareWoodcuttingBirch.dropTableId, RareWoodcuttingBirch],
    [RareWoodcuttingFinds.dropTableId, RareWoodcuttingFinds],
    [RareWoodcuttingOak.dropTableId, RareWoodcuttingOak],
    [RareWoodcuttingPine.dropTableId, RareWoodcuttingPine],
    [SawmillPlanks.dropTableId, SawmillPlanks],
    [WoodcuttingBirch.dropTableId, WoodcuttingBirch],
    [WoodcuttingOak.dropTableId, WoodcuttingOak],
    [WoodcuttingPine.dropTableId, WoodcuttingPine],
  ]);

  /**
   * Get a droptable by ID
   */
  static get(id: string): DropTable | undefined {
    return this.items.get(id);
  }

  /**
   * Check if a droptable exists
   */
  static has(id: string): boolean {
    return this.items.has(id);
  }

  /**
   * Get all droptables
   */
  static getAll(): DropTable[] {
    return Array.from(this.items.values());
  }

  /**
   * Get all droptable IDs
   */
  static getAllIds(): string[] {
    return Array.from(this.items.keys());
  }

  /**
   * Get the total number of droptables
   */
  static get size(): number {
    return this.items.size
  }
}
