/**
 * DropTables Registry - Central registry for all droptables
 * Auto-generated by scripts/generate-all-registries.ts
 * Generated: 2025-11-12T01:49:57.748Z
 * DO NOT EDIT MANUALLY
 */

import { DropTable } from '../../types/locations';

import { CombatBanditBasic } from './drop-tables/CombatBanditBasic';
import { CombatGoblinBasic } from './drop-tables/CombatGoblinBasic';
import { CombatWolfBasic } from './drop-tables/CombatWolfBasic';
import { FishingSalmon } from './drop-tables/FishingSalmon';
import { FishingShrimp } from './drop-tables/FishingShrimp';
import { HerbalismChamomile } from './drop-tables/HerbalismChamomile';
import { HerbalismDragonsBreath } from './drop-tables/HerbalismDragonsBreath';
import { HerbalismMandrake } from './drop-tables/HerbalismMandrake';
import { HerbalismMoonpetal } from './drop-tables/HerbalismMoonpetal';
import { HerbalismNettle } from './drop-tables/HerbalismNettle';
import { HerbalismSage } from './drop-tables/HerbalismSage';
import { MiningCopper } from './drop-tables/MiningCopper';
import { MiningTin } from './drop-tables/MiningTin';
import { RareFishing } from './drop-tables/RareFishing';
import { RareLowMining } from './drop-tables/RareLowMining';
import { RareWoodcutting } from './drop-tables/RareWoodcutting';
import { WoodcuttingOak } from './drop-tables/WoodcuttingOak';

/**
 * Central registry for all droptables
 */
export class DropTableRegistry {
  private static readonly items = new Map<string, DropTable>([
    [CombatBanditBasic.dropTableId, CombatBanditBasic],
    [CombatGoblinBasic.dropTableId, CombatGoblinBasic],
    [CombatWolfBasic.dropTableId, CombatWolfBasic],
    [FishingSalmon.dropTableId, FishingSalmon],
    [FishingShrimp.dropTableId, FishingShrimp],
    [HerbalismChamomile.dropTableId, HerbalismChamomile],
    [HerbalismDragonsBreath.dropTableId, HerbalismDragonsBreath],
    [HerbalismMandrake.dropTableId, HerbalismMandrake],
    [HerbalismMoonpetal.dropTableId, HerbalismMoonpetal],
    [HerbalismNettle.dropTableId, HerbalismNettle],
    [HerbalismSage.dropTableId, HerbalismSage],
    [MiningCopper.dropTableId, MiningCopper],
    [MiningTin.dropTableId, MiningTin],
    [RareFishing.dropTableId, RareFishing],
    [RareLowMining.dropTableId, RareLowMining],
    [RareWoodcutting.dropTableId, RareWoodcutting],
    [WoodcuttingOak.dropTableId, WoodcuttingOak],
  ]);

  /**
   * Get a droptable by ID
   */
  static get(id: string): DropTable | undefined {
    return this.items.get(id);
  }

  /**
   * Check if a droptable exists
   */
  static has(id: string): boolean {
    return this.items.has(id);
  }

  /**
   * Get all droptables
   */
  static getAll(): DropTable[] {
    return Array.from(this.items.values());
  }

  /**
   * Get all droptable IDs
   */
  static getAllIds(): string[] {
    return Array.from(this.items.keys());
  }

  /**
   * Get the total number of droptables
   */
  static get size(): number {
    return this.items.size
  }
}
