/**
 * Facilities Registry - Central registry for all facilities
 * Auto-generated by scripts/generate-all-registries.ts
 * Generated: 2025-11-12T01:49:55.338Z
 * DO NOT EDIT MANUALLY
 */

import { Facility } from '../../types/locations';

import { ForestBanditCamp } from './facilities/ForestBanditCamp';
import { ForestHerbGrove } from './facilities/ForestHerbGrove';
import { ForestLoggingCamp } from './facilities/ForestLoggingCamp';
import { GoblinCave } from './facilities/GoblinCave';
import { GoblinVillage } from './facilities/GoblinVillage';
import { KennikFishingDock } from './facilities/KennikFishingDock';
import { KennikForge } from './facilities/KennikForge';
import { KennikHerbGarden } from './facilities/KennikHerbGarden';
import { KennikKitchen } from './facilities/KennikKitchen';
import { KennikMarket } from './facilities/KennikMarket';
import { VillageApothecary } from './facilities/VillageApothecary';
import { MountainMine } from './facilities/MountainMine';
import { MountainMoonlitMeadow } from './facilities/MountainMoonlitMeadow';
import { VolcanicGarden } from './facilities/VolcanicGarden';

/**
 * Central registry for all facilities
 */
export class FacilityRegistry {
  private static readonly items = new Map<string, Facility>([
    [ForestBanditCamp.facilityId, ForestBanditCamp],
    [ForestHerbGrove.facilityId, ForestHerbGrove],
    [ForestLoggingCamp.facilityId, ForestLoggingCamp],
    [GoblinCave.facilityId, GoblinCave],
    [GoblinVillage.facilityId, GoblinVillage],
    [KennikFishingDock.facilityId, KennikFishingDock],
    [KennikForge.facilityId, KennikForge],
    [KennikHerbGarden.facilityId, KennikHerbGarden],
    [KennikKitchen.facilityId, KennikKitchen],
    [KennikMarket.facilityId, KennikMarket],
    [VillageApothecary.facilityId, VillageApothecary],
    [MountainMine.facilityId, MountainMine],
    [MountainMoonlitMeadow.facilityId, MountainMoonlitMeadow],
    [VolcanicGarden.facilityId, VolcanicGarden],
  ]);

  /**
   * Get a facility by ID
   */
  static get(id: string): Facility | undefined {
    return this.items.get(id);
  }

  /**
   * Check if a facility exists
   */
  static has(id: string): boolean {
    return this.items.has(id);
  }

  /**
   * Get all facilities
   */
  static getAll(): Facility[] {
    return Array.from(this.items.values());
  }

  /**
   * Get all facility IDs
   */
  static getAllIds(): string[] {
    return Array.from(this.items.keys());
  }

  /**
   * Get the total number of facilities
   */
  static get size(): number {
    return this.items.size
  }
}
