/**
 * Locations Registry - Central registry for all locations
 * Auto-generated by scripts/generate-all-registries.ts
 * Generated: 2025-11-18T01:41:54.825Z
 * DO NOT EDIT MANUALLY
 */

import { Location } from '../../types/locations';

import { ForestClearing } from './definitions/ForestClearing';
import { GoblinVillage } from './definitions/GoblinVillage';
import { Kennik } from './definitions/Kennik';
import { MountainPass } from './definitions/MountainPass';

/**
 * Central registry for all locations
 */
export class LocationRegistry {
  private static readonly items = new Map<string, Location>([
    [ForestClearing.locationId, ForestClearing],
    [GoblinVillage.locationId, GoblinVillage],
    [Kennik.locationId, Kennik],
    [MountainPass.locationId, MountainPass],
  ]);

  /**
   * Get a location by ID
   */
  static get(id: string): Location | undefined {
    return this.items.get(id);
  }

  /**
   * Check if a location exists
   */
  static has(id: string): boolean {
    return this.items.has(id);
  }

  /**
   * Get all locations
   */
  static getAll(): Location[] {
    return Array.from(this.items.values());
  }

  /**
   * Get all location IDs
   */
  static getAllIds(): string[] {
    return Array.from(this.items.keys());
  }

  /**
   * Get the total number of locations
   */
  static get size(): number {
    return this.items.size
  }
}
