/**
 * Abilities Registry - Central registry for all abilities
 * Auto-generated by scripts/generate-all-registries.ts
 * Generated: 2025-11-18T01:41:54.822Z
 * DO NOT EDIT MANUALLY
 */

import { Ability } from '../../types/combat';

import { AimedShot } from './definitions/AimedShot';
import { BattleFury } from './definitions/BattleFury';
import { DefensiveStance } from './definitions/DefensiveStance';
import { FireBolt } from './definitions/FireBolt';
import { HeavyStrike } from './definitions/HeavyStrike';
import { IceShard } from './definitions/IceShard';
import { PoisonStrike } from './definitions/PoisonStrike';
import { QuickSlash } from './definitions/QuickSlash';
import { RapidFire } from './definitions/RapidFire';
import { Regeneration } from './definitions/Regeneration';
import { WeakenArmor } from './definitions/WeakenArmor';

/**
 * Central registry for all abilities
 */
export class AbilityRegistry {
  private static readonly items = new Map<string, Ability>([
    [AimedShot.abilityId, AimedShot],
    [BattleFury.abilityId, BattleFury],
    [DefensiveStance.abilityId, DefensiveStance],
    [FireBolt.abilityId, FireBolt],
    [HeavyStrike.abilityId, HeavyStrike],
    [IceShard.abilityId, IceShard],
    [PoisonStrike.abilityId, PoisonStrike],
    [QuickSlash.abilityId, QuickSlash],
    [RapidFire.abilityId, RapidFire],
    [Regeneration.abilityId, Regeneration],
    [WeakenArmor.abilityId, WeakenArmor],
  ]);

  /**
   * Get a ability by ID
   */
  static get(id: string): Ability | undefined {
    return this.items.get(id);
  }

  /**
   * Check if a ability exists
   */
  static has(id: string): boolean {
    return this.items.has(id);
  }

  /**
   * Get all abilities
   */
  static getAll(): Ability[] {
    return Array.from(this.items.values());
  }

  /**
   * Get all ability IDs
   */
  static getAllIds(): string[] {
    return Array.from(this.items.keys());
  }

  /**
   * Get the total number of abilities
   */
  static get size(): number {
    return this.items.size
  }
}
