/**
 * Monsters Registry - Central registry for all monsters
 * Auto-generated by scripts/generate-all-registries.ts
 * Generated: 2025-11-12T01:34:11.941Z
 * DO NOT EDIT MANUALLY
 */

import { Monster } from '../../types/combat';

import { BanditThug } from './definitions/BanditThug';
import { ForestWolf } from './definitions/ForestWolf';
import { GoblinWarrior } from './definitions/GoblinWarrior';
import { GoblinScout } from './definitions/GoblinScout';
import { GoblinShaman } from './definitions/GoblinShaman';

/**
 * Central registry for all monsters
 */
export class MonsterRegistry {
  private static readonly items = new Map<string, Monster>([
    [BanditThug.monsterId, BanditThug],
    [ForestWolf.monsterId, ForestWolf],
    [GoblinWarrior.monsterId, GoblinWarrior],
    [GoblinScout.monsterId, GoblinScout],
    [GoblinShaman.monsterId, GoblinShaman],
  ]);

  /**
   * Get a monster by ID
   */
  static get(id: string): Monster | undefined {
    return this.items.get(id);
  }

  /**
   * Check if a monster exists
   */
  static has(id: string): boolean {
    return this.items.has(id);
  }

  /**
   * Get all monsters
   */
  static getAll(): Monster[] {
    return Array.from(this.items.values());
  }

  /**
   * Get all monster IDs
   */
  static getAllIds(): string[] {
    return Array.from(this.items.keys());
  }

  /**
   * Get the total number of monsters
   */
  static get size(): number {
    return this.items.size
  }
}
