/**
 * Item Registry - Central registry for all item definitions
 * Auto-generated by scripts/generate-registry.ts
 * Generated: 2025-11-12T01:25:03.169Z
 * DO NOT EDIT MANUALLY
 */

import { Item } from '../../types/items';

// CONSUMABLES
import { CookedCod } from './definitions/consumables/CookedCod';
import { CookedSalmon } from './definitions/consumables/CookedSalmon';
import { CookedShrimp } from './definitions/consumables/CookedShrimp';
import { CookedTrout } from './definitions/consumables/CookedTrout';
import { HealthPotionMinor } from './definitions/consumables/HealthPotionMinor';
import { ManaPotionMinor } from './definitions/consumables/ManaPotionMinor';

// EQUIPMENT
import { BambooFishingRod } from './definitions/equipment/BambooFishingRod';
import { BronzeMiningPickaxe } from './definitions/equipment/BronzeMiningPickaxe';
import { BronzeWoodcuttingAxe } from './definitions/equipment/BronzeWoodcuttingAxe';
import { CopperSword } from './definitions/equipment/CopperSword';
import { HempCoif } from './definitions/equipment/HempCoif';
import { IronHelm } from './definitions/equipment/IronHelm';
import { IronMiningPickaxe } from './definitions/equipment/IronMiningPickaxe';
import { IronSword } from './definitions/equipment/IronSword';
import { IronWoodcuttingAxe } from './definitions/equipment/IronWoodcuttingAxe';
import { LeatherTunic } from './definitions/equipment/LeatherTunic';
import { RareIronMiningPickaxeOffhand } from './definitions/equipment/RareIronMiningPickaxeOffhand';
import { WillowFishingRod } from './definitions/equipment/WillowFishingRod';
import { WoodenShield } from './definitions/equipment/WoodenShield';

// RESOURCES
import { Amethyst } from './definitions/resources/Amethyst';
import { Aquamarine } from './definitions/resources/Aquamarine';
import { BronzeIngot } from './definitions/resources/BronzeIngot';
import { Chamomile } from './definitions/resources/Chamomile';
import { Citrine } from './definitions/resources/Citrine';
import { CopperOre } from './definitions/resources/CopperOre';
import { DragonsBreath } from './definitions/resources/DragonsBreath';
import { Emerald } from './definitions/resources/Emerald';
import { Garnet } from './definitions/resources/Garnet';
import { GoblinTooth } from './definitions/resources/GoblinTooth';
import { Honeysuckle } from './definitions/resources/Honeysuckle';
import { IronIngot } from './definitions/resources/IronIngot';
import { IronOre } from './definitions/resources/IronOre';
import { Jade } from './definitions/resources/Jade';
import { Jasmine } from './definitions/resources/Jasmine';
import { LeatherScraps } from './definitions/resources/LeatherScraps';
import { MandrakeRoot } from './definitions/resources/MandrakeRoot';
import { MapleLog } from './definitions/resources/MapleLog';
import { Moonpetal } from './definitions/resources/Moonpetal';
import { Moonvine } from './definitions/resources/Moonvine';
import { MorningGlory } from './definitions/resources/MorningGlory';
import { Nettle } from './definitions/resources/Nettle';
import { OakLog } from './definitions/resources/OakLog';
import { Passionflower } from './definitions/resources/Passionflower';
import { PhoenixVine } from './definitions/resources/PhoenixVine';
import { Pike } from './definitions/resources/Pike';
import { Quartz } from './definitions/resources/Quartz';
import { RawMeat } from './definitions/resources/RawMeat';
import { Ruby } from './definitions/resources/Ruby';
import { Sage } from './definitions/resources/Sage';
import { Salmon } from './definitions/resources/Salmon';
import { Sapphire } from './definitions/resources/Sapphire';
import { ScrapMetal } from './definitions/resources/ScrapMetal';
import { Shrimp } from './definitions/resources/Shrimp';
import { SilverOre } from './definitions/resources/SilverOre';
import { TatteredCloth } from './definitions/resources/TatteredCloth';
import { TinOre } from './definitions/resources/TinOre';
import { Topaz } from './definitions/resources/Topaz';
import { Trout } from './definitions/resources/Trout';
import { TrumpetVine } from './definitions/resources/TrumpetVine';
import { Turquoise } from './definitions/resources/Turquoise';
import { WillowLog } from './definitions/resources/WillowLog';
import { Wisteria } from './definitions/resources/Wisteria';
import { WolfFang } from './definitions/resources/WolfFang';
import { WolfPelt } from './definitions/resources/WolfPelt';

/**
 * Central registry for all item definitions
 */
export class ItemRegistry {
  private static readonly items = new Map<string, Item>([
    [CookedCod.itemId, CookedCod],
    [CookedSalmon.itemId, CookedSalmon],
    [CookedShrimp.itemId, CookedShrimp],
    [CookedTrout.itemId, CookedTrout],
    [HealthPotionMinor.itemId, HealthPotionMinor],
    [ManaPotionMinor.itemId, ManaPotionMinor],
    [BambooFishingRod.itemId, BambooFishingRod],
    [BronzeMiningPickaxe.itemId, BronzeMiningPickaxe],
    [BronzeWoodcuttingAxe.itemId, BronzeWoodcuttingAxe],
    [CopperSword.itemId, CopperSword],
    [HempCoif.itemId, HempCoif],
    [IronHelm.itemId, IronHelm],
    [IronMiningPickaxe.itemId, IronMiningPickaxe],
    [IronSword.itemId, IronSword],
    [IronWoodcuttingAxe.itemId, IronWoodcuttingAxe],
    [LeatherTunic.itemId, LeatherTunic],
    [RareIronMiningPickaxeOffhand.itemId, RareIronMiningPickaxeOffhand],
    [WillowFishingRod.itemId, WillowFishingRod],
    [WoodenShield.itemId, WoodenShield],
    [Amethyst.itemId, Amethyst],
    [Aquamarine.itemId, Aquamarine],
    [BronzeIngot.itemId, BronzeIngot],
    [Chamomile.itemId, Chamomile],
    [Citrine.itemId, Citrine],
    [CopperOre.itemId, CopperOre],
    [DragonsBreath.itemId, DragonsBreath],
    [Emerald.itemId, Emerald],
    [Garnet.itemId, Garnet],
    [GoblinTooth.itemId, GoblinTooth],
    [Honeysuckle.itemId, Honeysuckle],
    [IronIngot.itemId, IronIngot],
    [IronOre.itemId, IronOre],
    [Jade.itemId, Jade],
    [Jasmine.itemId, Jasmine],
    [LeatherScraps.itemId, LeatherScraps],
    [MandrakeRoot.itemId, MandrakeRoot],
    [MapleLog.itemId, MapleLog],
    [Moonpetal.itemId, Moonpetal],
    [Moonvine.itemId, Moonvine],
    [MorningGlory.itemId, MorningGlory],
    [Nettle.itemId, Nettle],
    [OakLog.itemId, OakLog],
    [Passionflower.itemId, Passionflower],
    [PhoenixVine.itemId, PhoenixVine],
    [Pike.itemId, Pike],
    [Quartz.itemId, Quartz],
    [RawMeat.itemId, RawMeat],
    [Ruby.itemId, Ruby],
    [Sage.itemId, Sage],
    [Salmon.itemId, Salmon],
    [Sapphire.itemId, Sapphire],
    [ScrapMetal.itemId, ScrapMetal],
    [Shrimp.itemId, Shrimp],
    [SilverOre.itemId, SilverOre],
    [TatteredCloth.itemId, TatteredCloth],
    [TinOre.itemId, TinOre],
    [Topaz.itemId, Topaz],
    [Trout.itemId, Trout],
    [TrumpetVine.itemId, TrumpetVine],
    [Turquoise.itemId, Turquoise],
    [WillowLog.itemId, WillowLog],
    [Wisteria.itemId, Wisteria],
    [WolfFang.itemId, WolfFang],
    [WolfPelt.itemId, WolfPelt],
  ]);

  /**
   * Get an item definition by ID
   */
  static get(itemId: string): Item | undefined {
    return this.items.get(itemId);
  }

  /**
   * Check if an item exists
   */
  static has(itemId: string): boolean {
    return this.items.has(itemId);
  }

  /**
   * Get all item definitions
   */
  static getAll(): Item[] {
    return Array.from(this.items.values());
  }

  /**
   * Get all item IDs
   */
  static getAllIds(): string[] {
    return Array.from(this.items.keys());
  }

  /**
   * Get items by category
   */
  static getByCategory(category: string): Item[] {
    return this.getAll().filter(item => item.category === category);
  }

  /**
   * Get items by subcategory
   */
  static getBySubcategory(subcategory: string): Item[] {
    return this.getAll().filter(item => item.subcategories?.includes(subcategory));
  }

  /**
   * Get the total number of items
   */
  static get size(): number {
    return this.items.size;
  }
}
