/**
 * Item Registry - Central registry for all item definitions
 * Auto-generated by scripts/generate-registry.ts
 * Generated: 2025-11-18T17:55:10.797Z
 * DO NOT EDIT MANUALLY
 */

import { Item } from '@shared/types';

// CONSUMABLES
import { CookedCod } from './definitions/consumables/CookedCod';
import { CookedSalmon } from './definitions/consumables/CookedSalmon';
import { CookedShrimp } from './definitions/consumables/CookedShrimp';
import { CookedTrout } from './definitions/consumables/CookedTrout';
import { FuryBrew } from './definitions/consumables/FuryBrew';
import { HealthDraught } from './definitions/consumables/HealthDraught';
import { HealthElixir } from './definitions/consumables/HealthElixir';
import { HealthTincture } from './definitions/consumables/HealthTincture';
import { ManaDraught } from './definitions/consumables/ManaDraught';
import { ManaTincture } from './definitions/consumables/ManaTincture';
import { PowerElixir } from './definitions/consumables/PowerElixir';
import { VigorDraught } from './definitions/consumables/VigorDraught';
import { WardingTonic } from './definitions/consumables/WardingTonic';

// EQUIPMENT
import { BambooFishingRod } from './definitions/equipment/BambooFishingRod';
import { BronzeBoots } from './definitions/equipment/BronzeBoots';
import { BronzeGloves } from './definitions/equipment/BronzeGloves';
import { BronzeHelm } from './definitions/equipment/BronzeHelm';
import { BronzeMiningPickaxe } from './definitions/equipment/BronzeMiningPickaxe';
import { BronzePlate } from './definitions/equipment/BronzePlate';
import { BronzeSword } from './definitions/equipment/BronzeSword';
import { BronzeWoodcuttingAxe } from './definitions/equipment/BronzeWoodcuttingAxe';
import { HempCoif } from './definitions/equipment/HempCoif';
import { IronBattleaxe } from './definitions/equipment/IronBattleaxe';
import { IronBoots } from './definitions/equipment/IronBoots';
import { IronGloves } from './definitions/equipment/IronGloves';
import { IronGreatsword } from './definitions/equipment/IronGreatsword';
import { IronHelm } from './definitions/equipment/IronHelm';
import { IronMiningPickaxe } from './definitions/equipment/IronMiningPickaxe';
import { IronPlate } from './definitions/equipment/IronPlate';
import { IronSword } from './definitions/equipment/IronSword';
import { IronWoodcuttingAxe } from './definitions/equipment/IronWoodcuttingAxe';
import { LeatherTunic } from './definitions/equipment/LeatherTunic';
import { RareIronMiningPickaxeOffhand } from './definitions/equipment/RareIronMiningPickaxeOffhand';
import { WillowFishingRod } from './definitions/equipment/WillowFishingRod';
import { WoodenShield } from './definitions/equipment/WoodenShield';

// RESOURCES
import { Amber } from './definitions/resources/Amber';
import { Amethyst } from './definitions/resources/Amethyst';
import { Aquamarine } from './definitions/resources/Aquamarine';
import { BirchBark } from './definitions/resources/BirchBark';
import { BirchLog } from './definitions/resources/BirchLog';
import { BronzeIngot } from './definitions/resources/BronzeIngot';
import { CabbageSeeds } from './definitions/resources/CabbageSeeds';
import { CarrotSeeds } from './definitions/resources/CarrotSeeds';
import { Chamomile } from './definitions/resources/Chamomile';
import { Citrine } from './definitions/resources/Citrine';
import { Cod } from './definitions/resources/Cod';
import { CopperOre } from './definitions/resources/CopperOre';
import { DragonsBreath } from './definitions/resources/DragonsBreath';
import { Emerald } from './definitions/resources/Emerald';
import { Garnet } from './definitions/resources/Garnet';
import { Glass } from './definitions/resources/Glass';
import { GoblinTooth } from './definitions/resources/GoblinTooth';
import { Honeysuckle } from './definitions/resources/Honeysuckle';
import { IronIngot } from './definitions/resources/IronIngot';
import { IronOre } from './definitions/resources/IronOre';
import { Jade } from './definitions/resources/Jade';
import { Jasmine } from './definitions/resources/Jasmine';
import { LeatherScraps } from './definitions/resources/LeatherScraps';
import { LettuceSeeds } from './definitions/resources/LettuceSeeds';
import { MandrakeRoot } from './definitions/resources/MandrakeRoot';
import { MapleLog } from './definitions/resources/MapleLog';
import { Moonpetal } from './definitions/resources/Moonpetal';
import { Moonvine } from './definitions/resources/Moonvine';
import { MorningGlory } from './definitions/resources/MorningGlory';
import { Nails } from './definitions/resources/Nails';
import { Nettle } from './definitions/resources/Nettle';
import { OakLog } from './definitions/resources/OakLog';
import { OnionSeeds } from './definitions/resources/OnionSeeds';
import { Passionflower } from './definitions/resources/Passionflower';
import { PhoenixVine } from './definitions/resources/PhoenixVine';
import { Pike } from './definitions/resources/Pike';
import { PineLog } from './definitions/resources/PineLog';
import { PineResin } from './definitions/resources/PineResin';
import { Planks } from './definitions/resources/Planks';
import { PotatoSeeds } from './definitions/resources/PotatoSeeds';
import { PumpkinSeeds } from './definitions/resources/PumpkinSeeds';
import { Quartz } from './definitions/resources/Quartz';
import { RawMeat } from './definitions/resources/RawMeat';
import { Ruby } from './definitions/resources/Ruby';
import { Sage } from './definitions/resources/Sage';
import { Salmon } from './definitions/resources/Salmon';
import { Sand } from './definitions/resources/Sand';
import { Sapphire } from './definitions/resources/Sapphire';
import { ScrapMetal } from './definitions/resources/ScrapMetal';
import { Shrimp } from './definitions/resources/Shrimp';
import { SilverOre } from './definitions/resources/SilverOre';
import { Stone } from './definitions/resources/Stone';
import { StrawberrySeeds } from './definitions/resources/StrawberrySeeds';
import { TatteredCloth } from './definitions/resources/TatteredCloth';
import { TinOre } from './definitions/resources/TinOre';
import { TomatoSeeds } from './definitions/resources/TomatoSeeds';
import { Topaz } from './definitions/resources/Topaz';
import { Trout } from './definitions/resources/Trout';
import { TrumpetVine } from './definitions/resources/TrumpetVine';
import { TurnipSeeds } from './definitions/resources/TurnipSeeds';
import { Turquoise } from './definitions/resources/Turquoise';
import { WillowLog } from './definitions/resources/WillowLog';
import { Wisteria } from './definitions/resources/Wisteria';
import { WolfFang } from './definitions/resources/WolfFang';
import { WolfPelt } from './definitions/resources/WolfPelt';

/**
 * Central registry for all item definitions
 */
export class ItemRegistry {
  private static readonly items = new Map<string, Item>([
    [CookedCod.itemId, CookedCod],
    [CookedSalmon.itemId, CookedSalmon],
    [CookedShrimp.itemId, CookedShrimp],
    [CookedTrout.itemId, CookedTrout],
    [FuryBrew.itemId, FuryBrew],
    [HealthDraught.itemId, HealthDraught],
    [HealthElixir.itemId, HealthElixir],
    [HealthTincture.itemId, HealthTincture],
    [ManaDraught.itemId, ManaDraught],
    [ManaTincture.itemId, ManaTincture],
    [PowerElixir.itemId, PowerElixir],
    [VigorDraught.itemId, VigorDraught],
    [WardingTonic.itemId, WardingTonic],
    [BambooFishingRod.itemId, BambooFishingRod],
    [BronzeBoots.itemId, BronzeBoots],
    [BronzeGloves.itemId, BronzeGloves],
    [BronzeHelm.itemId, BronzeHelm],
    [BronzeMiningPickaxe.itemId, BronzeMiningPickaxe],
    [BronzePlate.itemId, BronzePlate],
    [BronzeSword.itemId, BronzeSword],
    [BronzeWoodcuttingAxe.itemId, BronzeWoodcuttingAxe],
    [HempCoif.itemId, HempCoif],
    [IronBattleaxe.itemId, IronBattleaxe],
    [IronBoots.itemId, IronBoots],
    [IronGloves.itemId, IronGloves],
    [IronGreatsword.itemId, IronGreatsword],
    [IronHelm.itemId, IronHelm],
    [IronMiningPickaxe.itemId, IronMiningPickaxe],
    [IronPlate.itemId, IronPlate],
    [IronSword.itemId, IronSword],
    [IronWoodcuttingAxe.itemId, IronWoodcuttingAxe],
    [LeatherTunic.itemId, LeatherTunic],
    [RareIronMiningPickaxeOffhand.itemId, RareIronMiningPickaxeOffhand],
    [WillowFishingRod.itemId, WillowFishingRod],
    [WoodenShield.itemId, WoodenShield],
    [Amber.itemId, Amber],
    [Amethyst.itemId, Amethyst],
    [Aquamarine.itemId, Aquamarine],
    [BirchBark.itemId, BirchBark],
    [BirchLog.itemId, BirchLog],
    [BronzeIngot.itemId, BronzeIngot],
    [CabbageSeeds.itemId, CabbageSeeds],
    [CarrotSeeds.itemId, CarrotSeeds],
    [Chamomile.itemId, Chamomile],
    [Citrine.itemId, Citrine],
    [Cod.itemId, Cod],
    [CopperOre.itemId, CopperOre],
    [DragonsBreath.itemId, DragonsBreath],
    [Emerald.itemId, Emerald],
    [Garnet.itemId, Garnet],
    [Glass.itemId, Glass],
    [GoblinTooth.itemId, GoblinTooth],
    [Honeysuckle.itemId, Honeysuckle],
    [IronIngot.itemId, IronIngot],
    [IronOre.itemId, IronOre],
    [Jade.itemId, Jade],
    [Jasmine.itemId, Jasmine],
    [LeatherScraps.itemId, LeatherScraps],
    [LettuceSeeds.itemId, LettuceSeeds],
    [MandrakeRoot.itemId, MandrakeRoot],
    [MapleLog.itemId, MapleLog],
    [Moonpetal.itemId, Moonpetal],
    [Moonvine.itemId, Moonvine],
    [MorningGlory.itemId, MorningGlory],
    [Nails.itemId, Nails],
    [Nettle.itemId, Nettle],
    [OakLog.itemId, OakLog],
    [OnionSeeds.itemId, OnionSeeds],
    [Passionflower.itemId, Passionflower],
    [PhoenixVine.itemId, PhoenixVine],
    [Pike.itemId, Pike],
    [PineLog.itemId, PineLog],
    [PineResin.itemId, PineResin],
    [Planks.itemId, Planks],
    [PotatoSeeds.itemId, PotatoSeeds],
    [PumpkinSeeds.itemId, PumpkinSeeds],
    [Quartz.itemId, Quartz],
    [RawMeat.itemId, RawMeat],
    [Ruby.itemId, Ruby],
    [Sage.itemId, Sage],
    [Salmon.itemId, Salmon],
    [Sand.itemId, Sand],
    [Sapphire.itemId, Sapphire],
    [ScrapMetal.itemId, ScrapMetal],
    [Shrimp.itemId, Shrimp],
    [SilverOre.itemId, SilverOre],
    [Stone.itemId, Stone],
    [StrawberrySeeds.itemId, StrawberrySeeds],
    [TatteredCloth.itemId, TatteredCloth],
    [TinOre.itemId, TinOre],
    [TomatoSeeds.itemId, TomatoSeeds],
    [Topaz.itemId, Topaz],
    [Trout.itemId, Trout],
    [TrumpetVine.itemId, TrumpetVine],
    [TurnipSeeds.itemId, TurnipSeeds],
    [Turquoise.itemId, Turquoise],
    [WillowLog.itemId, WillowLog],
    [Wisteria.itemId, Wisteria],
    [WolfFang.itemId, WolfFang],
    [WolfPelt.itemId, WolfPelt],
  ]);

  /**
   * Get an item definition by ID
   */
  static get(itemId: string): Item | undefined {
    return this.items.get(itemId);
  }

  /**
   * Check if an item exists
   */
  static has(itemId: string): boolean {
    return this.items.has(itemId);
  }

  /**
   * Get all item definitions
   */
  static getAll(): Item[] {
    return Array.from(this.items.values());
  }

  /**
   * Get all item IDs
   */
  static getAllIds(): string[] {
    return Array.from(this.items.keys());
  }

  /**
   * Get items by category
   */
  static getByCategory(category: string): Item[] {
    return this.getAll().filter(item => item.category === category);
  }

  /**
   * Get items by subcategory
   */
  static getBySubcategory(subcategory: string): Item[] {
    return this.getAll().filter(item => item.subcategories?.includes(subcategory));
  }

  /**
   * Get the total number of items
   */
  static get size(): number {
    return this.items.size;
  }
}
