/**
 * Recipes Registry - Central registry for all recipes
 * Auto-generated by scripts/generate-all-registries.ts
 * Generated: 2025-11-12T01:34:11.948Z
 * DO NOT EDIT MANUALLY
 */

import { Recipe } from '../../types/crafting';

// COOKING
import { CookCod } from './cooking/CookCod';
import { CookSalmon } from './cooking/CookSalmon';
import { CookShrimp } from './cooking/CookShrimp';
import { CookTrout } from './cooking/CookTrout';

// SMITHING
import { SmeltBronzeIngot } from './smithing/SmeltBronzeIngot';
import { SmeltIronIngot } from './smithing/SmeltIronIngot';


/**
 * Central registry for all recipes
 */
export class RecipeRegistry {
  private static readonly items = new Map<string, Recipe>([
    [CookCod.recipeId, CookCod],
    [CookSalmon.recipeId, CookSalmon],
    [CookShrimp.recipeId, CookShrimp],
    [CookTrout.recipeId, CookTrout],
    [SmeltBronzeIngot.recipeId, SmeltBronzeIngot],
    [SmeltIronIngot.recipeId, SmeltIronIngot],
  ]);

  /**
   * Get a recipe by ID
   */
  static get(id: string): Recipe | undefined {
    return this.items.get(id);
  }

  /**
   * Check if a recipe exists
   */
  static has(id: string): boolean {
    return this.items.has(id);
  }

  /**
   * Get all recipes
   */
  static getAll(): Recipe[] {
    return Array.from(this.items.values());
  }

  /**
   * Get all recipe IDs
   */
  static getAllIds(): string[] {
    return Array.from(this.items.keys());
  }

  /**
   * Get the total number of recipes
   */
  static get size(): number {
    return this.items.size
  }
}
