/**
 * Recipes Registry - Central registry for all recipes
 * Auto-generated by scripts/generate-all-registries.ts
 * Generated: 2025-11-12T03:46:00.032Z
 * DO NOT EDIT MANUALLY
 */

import { Recipe } from '../../types/crafting';

// COOKING
import { CookCod } from './cooking/CookCod';
import { CookSalmon } from './cooking/CookSalmon';
import { CookShrimp } from './cooking/CookShrimp';
import { CookTrout } from './cooking/CookTrout';

// SMITHING
import { ForgeBronzeBoots } from './smithing/ForgeBronzeBoots';
import { ForgeBronzeGloves } from './smithing/ForgeBronzeGloves';
import { ForgeBronzeHelm } from './smithing/ForgeBronzeHelm';
import { ForgeBronzeMiningPickaxe } from './smithing/ForgeBronzeMiningPickaxe';
import { ForgeBronzePlate } from './smithing/ForgeBronzePlate';
import { ForgeBronzeSword } from './smithing/ForgeBronzeSword';
import { ForgeBronzeWoodcuttingAxe } from './smithing/ForgeBronzeWoodcuttingAxe';
import { ForgeIronBoots } from './smithing/ForgeIronBoots';
import { ForgeIronGloves } from './smithing/ForgeIronGloves';
import { ForgeIronHelm } from './smithing/ForgeIronHelm';
import { ForgeIronMiningPickaxe } from './smithing/ForgeIronMiningPickaxe';
import { ForgeIronPlate } from './smithing/ForgeIronPlate';
import { ForgeIronSword } from './smithing/ForgeIronSword';
import { ForgeIronWoodcuttingAxe } from './smithing/ForgeIronWoodcuttingAxe';
import { SmeltBronzeIngot } from './smithing/SmeltBronzeIngot';
import { SmeltIronIngot } from './smithing/SmeltIronIngot';


/**
 * Central registry for all recipes
 */
export class RecipeRegistry {
  private static readonly items = new Map<string, Recipe>([
    [CookCod.recipeId, CookCod],
    [CookSalmon.recipeId, CookSalmon],
    [CookShrimp.recipeId, CookShrimp],
    [CookTrout.recipeId, CookTrout],
    [ForgeBronzeBoots.recipeId, ForgeBronzeBoots],
    [ForgeBronzeGloves.recipeId, ForgeBronzeGloves],
    [ForgeBronzeHelm.recipeId, ForgeBronzeHelm],
    [ForgeBronzeMiningPickaxe.recipeId, ForgeBronzeMiningPickaxe],
    [ForgeBronzePlate.recipeId, ForgeBronzePlate],
    [ForgeBronzeSword.recipeId, ForgeBronzeSword],
    [ForgeBronzeWoodcuttingAxe.recipeId, ForgeBronzeWoodcuttingAxe],
    [ForgeIronBoots.recipeId, ForgeIronBoots],
    [ForgeIronGloves.recipeId, ForgeIronGloves],
    [ForgeIronHelm.recipeId, ForgeIronHelm],
    [ForgeIronMiningPickaxe.recipeId, ForgeIronMiningPickaxe],
    [ForgeIronPlate.recipeId, ForgeIronPlate],
    [ForgeIronSword.recipeId, ForgeIronSword],
    [ForgeIronWoodcuttingAxe.recipeId, ForgeIronWoodcuttingAxe],
    [SmeltBronzeIngot.recipeId, SmeltBronzeIngot],
    [SmeltIronIngot.recipeId, SmeltIronIngot],
  ]);

  /**
   * Get a recipe by ID
   */
  static get(id: string): Recipe | undefined {
    return this.items.get(id);
  }

  /**
   * Check if a recipe exists
   */
  static has(id: string): boolean {
    return this.items.has(id);
  }

  /**
   * Get all recipes
   */
  static getAll(): Recipe[] {
    return Array.from(this.items.values());
  }

  /**
   * Get all recipe IDs
   */
  static getAllIds(): string[] {
    return Array.from(this.items.keys());
  }

  /**
   * Get the total number of recipes
   */
  static get size(): number {
    return this.items.size
  }
}
